### ISSUE TITLE
Colored logs import issue

### ISSUE THREAD

**Issue by niparis** [bmwant/podmena#1]
right after installing podmena, i ran into the following issue:

```
➜  ~ podmena add global   
Traceback (most recent call last):
  File "/usr/local/bin/podmena", line 7, in <module>
    from podmena.cli import cli
  File "/usr/local/lib/python3.6/site-packages/podmena/cli.py", line 7, in <module>
    from podmena.fetcher import SimpleFetcher
  File "/usr/local/lib/python3.6/site-packages/podmena/fetcher.py", line 8, in <module>
    from podmena.utils import get_logger
  File "/usr/local/lib/python3.6/site-packages/podmena/utils.py", line 6, in <module>
    import coloredlogs
ModuleNotFoundError: No module named 'coloredlogs'
```

Looks like `coloredlogs` should be a standard dependency and not just for dev

**Comment by bmwant** [comment]
@niparis Thanks for your feedback! This issue has been already fixed with `0.4.0` version. You can `pip install podmena --upgrade` it and get rid of an error. 
New features are available as well: 

- printing current version with `podmena --version`
- showing status on repos/globally with `podmena status`
